apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
        - name: my-nginx
          image: harbor.od.com/public/nginx:v1.7.9
          ports:
            - containerPort: 80
